### ISSUE TITLE
should output the ca cert

### ISSUE THREAD

**Issue by tcskill** [cloud-native-toolkit/terraform-gitops-mongo-ce#16]
original instance had an output variable for the ca cert

**Comment by tcskill** [comment]
here's what the lab is doing - what we need
https://github.com/ibm-watson-iot/iot-docs/blob/master/mongodb/certs/generateSelfSignedCert.sh

**Comment by tcskill** [comment]
@triceam other thing I noticed this is creating another cert manager on the cluster. MAS uses the cert-mgr in ibm common services, i have seen issues where there were two cert managers installed on the same cluster where mas can't find the route to the one it wants properly. don't know if this is going to be an issue but it definitely raises concern

**Comment by tcskill** [comment]
@triceam may be a combination errors with the cert-manager it installs with this, sls doesn't seem to like it as stated above ^^

**Comment by triceam** [comment]
The module cannot output the CA cert as it is currently implemented.  it does not know about it.  The cert is being created in-cluster using the cluster's cert issuer.   The module only creates the gitops repo and populates yaml, the cert is created once argo applies the gitops config to the cluster.
